tasks:
  - init: |
      python3 -m venv env
      export PIP_USER=no
      source ./env/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements_dev.txt
  - command: >
      while [ -z "$BOT_TOKEN" ] ; do
        printf "\n❗ The BOT_TOKEN environment variable is required. Please enter its value.\n" &&
        read -s -p "BOT_TOKEN: " BOT_TOKEN ;
      done ; gp env BOT_TOKEN=$BOT_TOKEN && printf "\nThanks\n"